### ISSUE TITLE
[HorizontalGroup] and [ReorderableList] conflict

### ISSUE THREAD

**Issue by jinsediaoying** [arimger/Unity-Editor-Toolbox#17]
```
[BeginHorizontal]
[ReorderableList]
public ParticleSystem[] particles;

[ReorderableList]
[EndHorizontal]
public float[] baseDelay;
```
![DP_XAHSSWG4Z_QS U{TTT)R](https://user-images.githubusercontent.com/25916527/124247715-b7a96580-db54-11eb-9133-a4e8f507e9d3.png)

**Comment by arimger** [comment]
Thanks, I will fix it.

**Comment by arimger** [comment]
Fix available on the master/upm branch.

![ro](https://user-images.githubusercontent.com/38333645/124350270-f5110000-dbf3-11eb-9f60-9e1c0ba6533c.PNG)

**Comment by jinsediaoying** [comment]
![image](https://user-images.githubusercontent.com/25916527/124351178-6ddf7e80-dc2b-11eb-9ad4-c29a486325ba.png)
It seems like that the horizontal space calculation is based on the list items count.

**Comment by jinsediaoying** [comment]
![GTO}N2X$QA}~DC7YA{PT~{A](https://user-images.githubusercontent.com/25916527/124351235-ca429e00-dc2b-11eb-9548-de3a373ef2a0.png)
And non ReorderableList version list drawers with HorizontalGroup is still buggy.

**Comment by arimger** [comment]
I just pushed a fix to the development branch, but using HorizontalGroups may be a little bit tricky. You have to use **fieldToWidthRatio** and **labelToWidthRatio** to keep elements nice looking, if values are equal to 0 (default situation) field may look strange but the horizontal group should work properly.

```
    [BeginHorizontal(fieldToWidthRatio: 0.2f, labelToWidthRatio: 0.2f)]
    public int[] ints1;
    [EndHorizontal]
    public int[] ints2;
```

Unfortunately, groups don't know how many elements are inside, that's why you have to adjust ratios.

**Comment by arimger** [comment]
One small update - I added [Begin/EndHorizontalGroup] to mirror the functionality of the [Begin/EndGroup] but for horizontal controls.
![horizontal](https://user-images.githubusercontent.com/38333645/124401103-e6c40080-dd27-11eb-9388-b4e2a07e3e6c.png)

**Comment by jinsediaoying** [comment]
```
public class Test : MonoBehaviour
{
	[BeginHorizontalGroup]
	public int x;

	[EndHorizontalGroup]
	public int y;
}
```
![~67ZDRC98 @%)KN~EGZQ}_D](https://user-images.githubusercontent.com/25916527/124428453-52958000-dd9f-11eb-84d9-eee3360d8a19.png)

Looks not working?

**Comment by jinsediaoying** [comment]
The fieldToWidthRatio/labelToWidthRatio thing is confusing, it that means I have to calculate the width based on the item count per row manually?

**Comment by arimger** [comment]
Are you sure you have [Begin/EndHorizontalGroup] available in the settings file (Edit/Project Settings.../Editor Toolbox/Inspector)?  
![image](https://user-images.githubusercontent.com/38333645/124433434-07657800-dd73-11eb-955e-ce5ef00a5c58.png)

About fieldToWidthRatio/labelToWidthRatio - it means you can (it's not necessary) adjust the width of labels and fields within horizontal groups.
![ratio](https://user-images.githubusercontent.com/38333645/124434321-08e37000-dd74-11eb-8514-1b441ff3613e.png)
In this example labelToWidthRatio = 0.1f, it means that every label will try to fill space equal to width * 0.1f.

**Comment by jinsediaoying** [comment]
Soru, I forget to change the ProjectSetting, It now looks correct.

**Comment by arimger** [comment]
Do you have any other troubles using horizontal groups?
